"""added incident answer time created

Revision ID: 026c90d613b7
Revises: 156fbc4b115d
Create Date: 2026-05-08 11:15:03.355506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026c90d613b7'
down_revision: Union[str, Sequence[str], None] = '156fbc4b115d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents_and_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents_and_answers',
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incident_answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['incident_answer_id'], ['incident_answers.id'], name=op.f('incidents_and_answers_incident_answer_id_fkey')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('incidents_and_answers_incident_id_fkey')),
    sa.PrimaryKeyConstraint('incident_id', 'incident_answer_id', name=op.f('incidents_and_answers_pkey'))
    )
    # ### end Alembic commands ###
