"""added camera type map color

Revision ID: 02b88119984c
Revises: 0ed687fdb2a6
Create Date: 2026-04-20 11:57:31.780168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b88119984c'
down_revision: Union[str, Sequence[str], None] = '0ed687fdb2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_types', sa.Column('map_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom_types', 'map_color')
    # ### end Alembic commands ###
