"""removed camera type

Revision ID: 0ed687fdb2a6
Revises: 5bdda92f4ec9
Create Date: 2026-04-13 17:20:40.130035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed687fdb2a6'
down_revision: Union[str, Sequence[str], None] = '5bdda92f4ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'camera_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('camera_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
