"""added polygon maps and pos

Revision ID: 1345f28c18ad
Revises: 892a409e505c
Create Date: 2026-03-29 21:29:18.425538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1345f28c18ad'
down_revision: Union[str, Sequence[str], None] = '892a409e505c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('pos_x', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('pos_y', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('polygon_map', sa.String(), nullable=True))
    op.add_column('classrooms', sa.Column('polygon_map', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'polygon_map')
    op.drop_column('cameras', 'polygon_map')
    op.drop_column('cameras', 'pos_y')
    op.drop_column('cameras', 'pos_x')
    # ### end Alembic commands ###
