"""added incident answers

Revision ID: 156fbc4b115d
Revises: 9be5cac62bb6
Create Date: 2026-05-07 12:13:17.339799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156fbc4b115d'
down_revision: Union[str, Sequence[str], None] = '9be5cac62bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents_and_answers',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('incident_answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_answer_id'], ['incident_answers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'incident_answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents_and_answers')
    op.drop_table('incident_answers')
    # ### end Alembic commands ###
