"""added event type in incident types

Revision ID: 1e4d949ef568
Revises: 8bc705048b14
Create Date: 2026-06-01 13:51:33.678764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4d949ef568'
down_revision: Union[str, Sequence[str], None] = '8bc705048b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_types', sa.Column('event_type', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_user_email_lower'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=False)
    op.drop_column('incident_types', 'event_type')
    # ### end Alembic commands ###
