"""cameras update

Revision ID: 354ff29bd18b
Revises: b84735691e09
Create Date: 2026-02-14 23:28:59.558622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354ff29bd18b'
down_revision: Union[str, Sequence[str], None] = 'b84735691e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cameras', 'camera_ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cameras', 'reg_ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cameras', 'view',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('schedule', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cameras', 'view',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cameras', 'reg_ip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cameras', 'camera_ip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
