"""renamed group size

Revision ID: 40c9fbc32b2e
Revises: 61d2e980cbdc
Create Date: 2026-06-05 11:42:42.320119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c9fbc32b2e'
down_revision: Union[str, Sequence[str], None] = '61d2e980cbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_size', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_groups_enrollment'), table_name='groups')
    op.create_index(op.f('ix_groups_group_size'), 'groups', ['group_size'], unique=False)
    op.drop_column('groups', 'enrollment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('enrollment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_groups_group_size'), table_name='groups')
    op.create_index(op.f('ix_groups_enrollment'), 'groups', ['enrollment'], unique=False)
    op.drop_column('groups', 'group_size')
    # ### end Alembic commands ###
