"""added array of cameras

Revision ID: 4c6f5891f004
Revises: bf1802a63195
Create Date: 2026-02-16 22:01:28.264188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6f5891f004'
down_revision: Union[str, Sequence[str], None] = 'bf1802a63195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('cameras_ids', sa.ARRAY(sa.INTEGER()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'cameras_ids')
    # ### end Alembic commands ###
