"""added incident answer time created fix

Revision ID: 538ab8166530
Revises: 026c90d613b7
Create Date: 2026-05-08 11:21:34.518196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538ab8166530'
down_revision: Union[str, Sequence[str], None] = '026c90d613b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_answers', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_answers', 'time_created')
    # ### end Alembic commands ###
