"""added classroom types

Revision ID: 5bdda92f4ec9
Revises: 58fad2c6067d
Create Date: 2026-04-13 15:10:17.551753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdda92f4ec9'
down_revision: Union[str, Sequence[str], None] = '58fad2c6067d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('classrooms', sa.Column('type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classrooms', 'classroom_types', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'type')
    op.drop_table('classroom_types')
    # ### end Alembic commands ###
