"""added preview rtsp url for cameras

Revision ID: 60670b6d7cb2
Revises: 1345f28c18ad
Create Date: 2026-04-06 14:06:49.405442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60670b6d7cb2'
down_revision: Union[str, Sequence[str], None] = '1345f28c18ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_url_preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'rtsp_url_preview')
    # ### end Alembic commands ###
