"""added enrollment for group

Revision ID: 61d2e980cbdc
Revises: bc9b3dc193ae
Create Date: 2026-06-05 11:23:12.269654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d2e980cbdc'
down_revision: Union[str, Sequence[str], None] = 'bc9b3dc193ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('enrollment', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_groups_enrollment'), 'groups', ['enrollment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_enrollment'), table_name='groups')
    op.drop_column('groups', 'enrollment')
    # ### end Alembic commands ###
