"""added number of floors

Revision ID: 892a409e505c
Revises: cea45797d234
Create Date: 2026-03-29 21:14:21.650267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892a409e505c'
down_revision: Union[str, Sequence[str], None] = 'cea45797d234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('number_of_floors', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'number_of_floors')
    # ### end Alembic commands ###
