"""lower email for user

Revision ID: 8bc705048b14
Revises: 3ae0a5f01b6f
Create Date: 2026-05-29 15:15:29.565322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc705048b14'
down_revision: Union[str, Sequence[str], None] = '3ae0a5f01b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email_lower', 'users', [sa.literal_column('lower(email)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email_lower', table_name='users')
    # ### end Alembic commands ###
