"""added keycloak uuid field for user

Revision ID: 901e56f0d47c
Revises: f6a6d1bc04f8
Create Date: 2026-05-28 15:58:39.170427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901e56f0d47c'
down_revision: Union[str, Sequence[str], None] = 'f6a6d1bc04f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keycloak_uuid')
    # ### end Alembic commands ###
