"""added bearer token field

Revision ID: 9be5cac62bb6
Revises: d36b99983119
Create Date: 2026-05-06 11:58:58.142852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be5cac62bb6'
down_revision: Union[str, Sequence[str], None] = 'd36b99983119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bearer_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bearer_token')
    # ### end Alembic commands ###
