"""added teacher to group realtionship

Revision ID: bc9b3dc193ae
Revises: 1e4d949ef568
Create Date: 2026-06-04 13:57:03.945895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9b3dc193ae'
down_revision: Union[str, Sequence[str], None] = '1e4d949ef568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'teacher_id')
    # ### end Alembic commands ###
