"""fix incidents

Revision ID: bf1802a63195
Revises: bfd5092d096e
Create Date: 2026-02-15 16:38:00.401334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf1802a63195'
down_revision: Union[str, Sequence[str], None] = 'bfd5092d096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('status', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.drop_constraint(op.f('incidents_classroom_id_fkey'), 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'classroom_id')
    op.add_column('schedule', sa.Column('timestamp_end', sa.DateTime(), nullable=False))
    op.drop_column('schedule', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_column('schedule', 'timestamp_end')
    op.add_column('incidents', sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('incidents_classroom_id_fkey'), 'incidents', 'classrooms', ['classroom_id'], ['id'])
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_column('incidents', 'status')
    # ### end Alembic commands ###
