"""added role display name

Revision ID: cea45797d234
Revises: f646273ac9d0
Create Date: 2026-03-26 12:21:41.969114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea45797d234'
down_revision: Union[str, Sequence[str], None] = 'f646273ac9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'state')
    op.add_column('roles', sa.Column('display_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_roles_display_name'), 'roles', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_display_name'), table_name='roles')
    op.drop_column('roles', 'display_name')
    op.add_column('cameras', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
