"""added incident types

Revision ID: d36b99983119
Revises: 02b88119984c
Create Date: 2026-04-27 16:15:17.349753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b99983119'
down_revision: Union[str, Sequence[str], None] = '02b88119984c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status_binding', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents_and_types',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('incident_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['incident_type_id'], ['incident_types.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'incident_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents_and_types')
    op.drop_table('incident_types')
    # ### end Alembic commands ###
