"""rtsp

Revision ID: e27b996a0d90
Revises: cd5b6d5a3024
Create Date: 2026-02-12 12:14:21.051013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e27b996a0d90'
down_revision: Union[str, Sequence[str], None] = 'cd5b6d5a3024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_url', sa.String(), nullable=False))
    op.drop_column('cameras', 'rtsp_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('cameras', 'rtsp_url')
    # ### end Alembic commands ###
