"""added array of cameras screenshots

Revision ID: f646273ac9d0
Revises: 4c6f5891f004
Create Date: 2026-02-16 23:05:59.237656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f646273ac9d0'
down_revision: Union[str, Sequence[str], None] = '4c6f5891f004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('cameras_screenshots', sa.ARRAY(sa.VARCHAR()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'cameras_screenshots')
    # ### end Alembic commands ###
