"""added event_type in schedule

Revision ID: f6a6d1bc04f8
Revises: 538ab8166530
Create Date: 2026-05-27 17:12:31.760423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a6d1bc04f8'
down_revision: Union[str, Sequence[str], None] = '538ab8166530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('event_type', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'event_type')
    # ### end Alembic commands ###
